version: '3'
services:
  utils:
    image: cloud_utils:latest
    container_name: cloud_utils
    build: .
    volumes:
    - /mnt/c/projects:/mnt/c/projects
    - /mnt/c/users/chwieder/.azure:/root/.azure
    - /mnt/c/users/chwieder/.git:/root/.config/git